
security:
  oauth2:
    resource:
#      jwt:
#        key-value: 123
      user-info-uri: http://localhost:9090/auth/account/user-info
      prefer-token-info: false


management.endpoints.web.exposure.include: "*"
server:
  use-forward-headers: true
  port: 4040
